# Generated by Django 6.0.2 on 2026-04-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_bio_user_github_user_linkedin_user_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='avatars', verbose_name='Аватар'),
        ),
    ]
