# Generated by Django 6.0.2 on 2026-04-12 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Новый чат', max_length=255, verbose_name='Название чата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('is_archived', models.BooleanField(default=False, help_text='Скрыть из основного списка, но не удалять', verbose_name='Архивирован')),
                ('message_count', models.PositiveIntegerField(default=0, verbose_name='Количество сообщений')),
                ('model_name', models.CharField(blank=True, default='gpt-3.5-turbo', max_length=50, verbose_name='Используемая модель')),
                ('system_prompt', models.TextField(blank=True, default='', help_text='Инструкция для нейросети в этом чате', verbose_name='Системный промпт')),
                ('temperature', models.FloatField(default=0.7, help_text='От 0 до 2. Выше - более креативные ответы', verbose_name='Температура')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('assistant', 'Ассистент'), ('system', 'Системное'), ('error', 'Ошибка')], db_index=True, default='user', max_length=20, verbose_name='Роль')),
                ('content', models.TextField(verbose_name='Текст сообщения')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время отправки')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'Обрабатывается'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='completed', max_length=20, verbose_name='Статус')),
                ('tokens_used', models.PositiveIntegerField(blank=True, null=True, verbose_name='Использовано токенов')),
                ('processing_time', models.FloatField(blank=True, null=True, verbose_name='Время обработки (сек)')),
                ('provider', models.CharField(blank=True, default='', help_text='openai, anthropic, local, etc.', max_length=50, verbose_name='Провайдер')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Дополнительная информация (finish_reason, model и т.д.)', verbose_name='Метаданные')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Отредактировано')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='Время редактирования')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chat', verbose_name='Чат')),
                ('parent_message', models.ForeignKey(blank=True, help_text='Для отслеживания версий ответов', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='chat.message', verbose_name='Родительское сообщение')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['user', '-updated_at'], name='chat_chat_user_id_70bbd8_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['user', 'is_archived'], name='chat_chat_user_id_d93494_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'created_at'], name='chat_messag_chat_id_0c7b25_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'role'], name='chat_messag_chat_id_db64d8_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['status'], name='chat_messag_status_8c4650_idx'),
        ),
    ]
